### ISSUE TITLE
Connection terminated remotely

### ISSUE THREAD

**Issue by tarsc** [cisco-ce/jsxapi#65] opened 2020-08-11 17:45 UTC
Hey Guys, i'm having a trouble while i'm doing an UI update.

i have a panel that i'm updating with new products list, but when its larger than 3 products this error shows up 'Connection terminated remotely'

do you guys have an idea how can i handle that ? i'm new working with cisco devices.

i'm not on vpn, im doing that local

i have this code as example 

```javascript
const jsxapi = require('jsxapi');
jsxapi
    .connect('ssh://roomkitip', {
        username: 'user',
        password: 'password'
    }).on('error', async (error) => {
        console.log(error)
    }).on('ready', async (xapi) => {

        let products= [{
            codigo: 'agua',
            nome: 'Water',
        }, {
            codigo: 'cafe',
            nome: 'Coffee',
        }, {
            codigo: 'cha',
            nome: 'Tea',
        }, {
            codigo: 'suco',
            nome: 'Juice',
        }, {
            codigo: 'coca',
            nome: 'Coke',
        },];

        xapi.command('UserInterface Extensions Panel Save', { PanelId: 'concierge' },
            `<Extensions>
                <Version>1.1</Version>
                <Name>Concierge</Name>
                <Panel>
                    <Icon>Concierge</Icon>
                    <Color>#FF3D67</Color>
                    <Name>Concierge</Name>
                    <Type>Statusbar</Type>
                    <Page>
                        <Name>Concierge</Name>
                        ${ produtos.map(el => {
                return `<Row>
                                    <Name>${el.nome}</Name>
                                    <Widget>
                                    <WidgetId>${el.codigo}</WidgetId>
                                    <Type>Spinner</Type>
                                    <Options>style=plusminus</Options>
                                    </Widget>
                                </Row>`}).join('')}
                    </Page>
                </Panel>
            </Extensions>`).then(res => {
                    console.log('result => ', res)
                }).catch(err => {
                    console.log('erro => ', err)

                });
    });
```

**Comment by torkildr** [comment] 2020-08-12 06:50
Very strange behavior indeed. We'll try to look into this.

**Comment by myme** [comment] 2020-08-12 09:50
This has been confirmed to be an issue with data payloads over ~2040 bytes in size when using `ssh`. If you can, please try to switch over to using WebSockets. Otherwise this has to be resolved in the device software. The root cause is not a `jsxapi` issue.

**Comment by torkildr** [comment] 2020-08-12 11:37
As @myme mentioned, the bug is in the device software, so will close this here.

We've filed an issue and following up fixing the bug at the source, but little we can do here except wait or use a workaround as mentioned.

**Closed by torkildr** 2020-08-12 11:37 UTC
Labels: bug
